from __future__ import annotations

from typing import Protocol, Any, Optional, Sequence, Mapping


Filters = Mapping[str, Any]
Payload = Mapping[str, Any]


class LeagueRepo(Protocol):
    """
    Kontrakt (interfejs) repozytorium dla warstwy widoków.
    Adaptery (mock/postgres/mongo) mają implementować to samo API.
    """

    # ---- Browse + search ----
    def list_leagues(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_league(self, league_id: int) -> Optional[Mapping[str, Any]]: ...

    def list_teams(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_team(self, team_id: int) -> Optional[Mapping[str, Any]]: ...

    def list_players(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_player(self, player_id: int) -> Optional[Mapping[str, Any]]: ...
    def team_players(self, team_id: int) -> Sequence[Mapping[str, Any]]: ...

    def list_matches(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_match(self, match_id: int) -> Optional[Mapping[str, Any]]: ...

    # ---- Helpers (formatowanie) ----
    def match_label(self, match: Mapping[str, Any]) -> str: ...

    # ---- Admin CRUD (na razie może być no-op w mocku) ----
    def create_league(self, data: Payload) -> Mapping[str, Any]: ...
    def update_league(self, league_id: int, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_league(self, league_id: int) -> bool: ...

    def create_team(self, data: Payload) -> Mapping[str, Any]: ...
    def update_team(self, team_id: int, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_team(self, team_id: int) -> bool: ...

    def create_player(self, data: Payload) -> Mapping[str, Any]: ...
    def update_player(self, player_id: int, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_player(self, player_id: int) -> bool: ...

    def create_match(self, data: Payload) -> Mapping[str, Any]: ...
    def update_match(self, match_id: int, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_match(self, match_id: int) -> bool: ...
