from __future__ import annotations
from typing import Protocol, Any, Optional, Sequence, Mapping

Filters = Mapping[str, Any]
Payload = Mapping[str, Any]
Id = str  # 24-char hex

class LeagueRepo(Protocol):
    def list_leagues(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_league(self, league_id: Id) -> Optional[Mapping[str, Any]]: ...

    def list_teams(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_team(self, team_id: Id) -> Optional[Mapping[str, Any]]: ...

    def list_players(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_player(self, player_id: Id) -> Optional[Mapping[str, Any]]: ...
    def team_players(self, team_id: Id) -> Sequence[Mapping[str, Any]]: ...

    def list_matches(self, *, q: Optional[str] = None, filters: Optional[Filters] = None) -> Sequence[Mapping[str, Any]]: ...
    def get_match(self, match_id: Id) -> Optional[Mapping[str, Any]]: ...

    def match_label(self, match: Mapping[str, Any]) -> str: ...

    def create_league(self, data: Payload) -> Mapping[str, Any]: ...
    def update_league(self, league_id: Id, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_league(self, league_id: Id) -> bool: ...

    def create_team(self, data: Payload) -> Mapping[str, Any]: ...
    def update_team(self, team_id: Id, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_team(self, team_id: Id) -> bool: ...

    def create_player(self, data: Payload) -> Mapping[str, Any]: ...
    def update_player(self, player_id: Id, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_player(self, player_id: Id) -> bool: ...

    def create_match(self, data: Payload) -> Mapping[str, Any]: ...
    def update_match(self, match_id: Id, data: Payload) -> Mapping[str, Any] | None: ...
    def delete_match(self, match_id: Id) -> bool: ...
